name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-dev

      - name: Create release archive
        run: |
          zip -r laravel-lookbook.zip . -x "*.git*" "tests/*" "phpunit.xml" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: laravel-lookbook.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
